---
  - block:
    - name: Installation Information
      set_fact:
        product_dir: "{{ target }}/micro-integrator"
        product_tmp_dir: "{{ target }}/micro-integrator/tmp"
        carbon_home: "{{ target }}/micro-integrator/{{ product_name }}-{{ product_version }}"
        carbon_tmp_home: "{{ target }}/micro-integrator/tmp/{{ product_name }}-{{ product_version }}"

    # WSO2 Distribution
    - name: Create product directory
      file:
        path: "{{ product_dir }}"
        state: directory
        mode: 0755

    - name: Create product temp directory
      file:
        path: "{{ product_tmp_dir }}"
        state: directory
        mode: 0755

    - name: Unzip WSO2 Micro Integrator from local source
      unarchive:
        src: "{{ product_package_location }}/packs/{{ product_name }}-{{ product_version }}.zip"
        dest: "{{ product_tmp_dir }}"
        mode: u=rw,g=r,o=r
      when: pack_location == "local"

    - name: Unzip WSO2 Micro Integrator Package from remote source
      unarchive:
        src: "{{ remote_pack }}"
        dest: "{{ product_tmp_dir }}"
        mode: u=rw,g=r,o=r
        remote_src: yes
      when: pack_location == "remote"

    - name: Copy JDBC Driver
      copy:
        src: "{{ product_package_location }}/lib/{{ jdbc_driver }}"
        dest: "{{ carbon_tmp_home }}/lib"
      when: jdbc_driver is defined

    - name: Copy configuration templates
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ config_files }}"

    - name: Copy security file list for WSO2MI
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ security_file_list }}"
      when: security_file_list is defined

    - name: Create miscellaneous file directory
      file:
        path: "{{ misc_file_copy_location }}"
        state: directory
        mode: 0755
      when: misc_file_list is defined

    - name: Copy miscellaneous resources
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ misc_file_list }}"
      when: misc_file_list is defined

    - name: Change the owner of shared directory
      file:
        path: "{{ product_shared_dir }}"
        state: directory
        recurse: true
        owner: "{{ wso2_user }}"
        group: "{{ wso2_group }}"
        mode: 0755

    - name: Get the list of services
      service_facts:

    - name: Stop wso2mi as a service
      systemd:
        name: wso2mi
        state: stopped
      when: "'wso2mi.service' in services"

    - name: Remove registry symlink
      file:
        path: "{{ carbon_home }}/registry"
        state: absent

    - name: Remove server symlink
      file:
        path: "{{ carbon_home }}/repository/deployment/server"
        state: absent

    - name: Remove existing setup
      file:
        path: "{{ carbon_home }}"
        state: absent

    - name: Copy files from tmp to carbon_home
      copy: 
        remote_src: true
        src: "{{ carbon_tmp_home }}"
        dest: "{{ product_dir }}"

    - name: Remove tmp existing setup
      file:
        path: "{{ product_tmp_dir }}"
        state: absent

    - name: Change the owner of WSO2 directory
      file:
        path: "{{ product_dir }}"
        state: directory
        recurse: true
        owner: "{{ wso2_user }}"
        group: "{{ wso2_group }}"
        mode: 0755

    - name: Remove registry existing setup
      file:
        path: "{{ carbon_home }}/registry"
        state: absent

    - name: Remove server existing setup
      file:
        path: "{{ carbon_home }}/repository/deployment/server"
        state: absent

    - name: Create registry symbolic link 
      file: 
        src: "{{registry_link_path}}"
        path: "{{ carbon_home }}/registry"
        force: yes
        state: link     

    - name: Create server symbolic link 
      file: 
        src: "{{server_link_path}}"
        path: "{{ carbon_home }}/repository/deployment/server"
        force: yes
        state: link     

    - import_tasks: common-tasks/secure-vault.yml
      when: secure_vault_enabled|bool

    - name: Copy wso2mi service file
      template:
        src: "wso2mi.service.j2"
        dest: /etc/systemd/system/wso2mi.service

    - name: Start wso2mi as a service
      systemd:
        name: wso2mi
        state: started
        daemon_reload: yes

    become: true
    become_user: root
