---
  - block:
    - name: Create group
      group: name=wso2 state=present gid=802
      become: true

    - name: Add wso2carbon user
      user: name=wso2carbon shell=/bin/bash group=wso2 uid=802 non_unique=yes
      become: true

    - name: System performance tuning
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ performance_tuning_file_list }}"
      when: enable_performance_tuning|bool

    - name: Create Java directory
      file:
        path: "{{ java_home }}"
        state: directory
      when: setup_java_enabled|bool

    - name: Unarchive JDK distribution from local source
      unarchive:
        src: "{{ product_package_location }}/lib/{{ jdk_tar_name }}.tar.gz"
        dest: "{{ java_home }}"
        extra_opts: [--strip-components=1]
      when: pack_location == "local" and setup_java_enabled|bool

    - name: Unarchive JDK distribution from remote source
      unarchive:
        src: "{{ remote_jdk }}"
        dest: "{{ java_home }}"
        extra_opts: [--strip-components=1]
        remote_src: yes
      when: pack_location == "remote" and setup_java_enabled|bool

    - name: Create Java symbolic link
      file:
        src: "{{ java_home }}"
        dest: "{{ java_symlink }}"
        state: link

    - name: Install unzip package
      package:
        name: unzip
        state: present

    become: true
    become_user: root
